CREATE TABLE  "INSTANSI" 
   (	"ID_INSTANSI" VARCHAR2(7) NOT NULL ENABLE, 
	"NAMA_INSTANSI" VARCHAR2(50) NOT NULL ENABLE, 
	"ALAMAT_INSTANSI" VARCHAR2(100) NOT NULL ENABLE, 
	"KOTA_INSTANSI" VARCHAR2(50) NOT NULL ENABLE, 
	"PROVINSI_INSTANSI" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "INSTANSI_PK" PRIMARY KEY ("ID_INSTANSI")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "TENAGA_MEDIS" 
   (	"NIP" NUMBER(20,0) NOT NULL ENABLE, 
	"NAMA_LENGKAP_NAKES" VARCHAR2(50) NOT NULL ENABLE, 
	"JK_NAKES" CHAR(1) NOT NULL ENABLE, 
	"ALAMAT_NAKES" VARCHAR2(100) NOT NULL ENABLE, 
	"KOTA_NAKES" VARCHAR2(50) NOT NULL ENABLE, 
	"PROVINSI_NAKES" VARCHAR2(50) NOT NULL ENABLE, 
	"EMAIL_NAKES" VARCHAR2(50) NOT NULL ENABLE, 
	"NO_HP_NAKES" VARCHAR2(15) NOT NULL ENABLE, 
	"JABATAN" VARCHAR2(50) NOT NULL ENABLE, 
	"ID_INSTANSI" VARCHAR2(6), 
	 CONSTRAINT "TENAGA_MEDIS_PK" PRIMARY KEY ("NIP")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "REPORT" 
   (	"ID_LAPORAN" VARCHAR2(6) NOT NULL ENABLE, 
	"NIP" NUMBER(20,0), 
	"ID_INSTANSI" VARCHAR2(6), 
	 CONSTRAINT "REPORT_PK" PRIMARY KEY ("ID_LAPORAN")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "PESERTA_VAKSIN" 
   (	"NIK" NUMBER(20,0) NOT NULL ENABLE, 
	"NAMA_LENGKAP" CHAR(50) NOT NULL ENABLE, 
	"JK" CHAR(1) NOT NULL ENABLE, 
	"TGL_LAHIR" DATE NOT NULL ENABLE, 
	"ALAMAT" VARCHAR2(100) NOT NULL ENABLE, 
	"KOTA" VARCHAR2(50) NOT NULL ENABLE, 
	"PROVINSI" VARCHAR2(50) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(50) NOT NULL ENABLE, 
	"NO_HP" VARCHAR2(15) NOT NULL ENABLE, 
	"ID_INSTANSI" VARCHAR2(6), 
	"NIP" NUMBER(20,0), 
	 CONSTRAINT "PESERTA_VAKSIN_PK" PRIMARY KEY ("NIK")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "VACCINATION" 
   (	"ID_REGIST" VARCHAR2(6) NOT NULL ENABLE, 
	"TGL_VAKSIN" DATE NOT NULL ENABLE, 
	"DIAGNOSA" VARCHAR2(50) NOT NULL ENABLE, 
	"DOSIS_VAKSIN" NUMBER(5,0) NOT NULL ENABLE, 
	"NIK" NUMBER(20,0), 
	"NIP" NUMBER(20,0), 
	"ID_INSTANSI" VARCHAR2(6), 
	 CONSTRAINT "VACCINATION_PK" PRIMARY KEY ("ID_REGIST")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "VACCINE" 
   (	"ID_VAKSIN" VARCHAR2(6) NOT NULL ENABLE, 
	"JENIS_VAKSIN" VARCHAR2(25) NOT NULL ENABLE, 
	"TGL_TERIMA_VAKSIN" DATE NOT NULL ENABLE, 
	"TGL_KADALUARSA_VAKSIN" DATE NOT NULL ENABLE, 
	"JML_VAKSIN_TERSEDIA" NUMBER(5,0) NOT NULL ENABLE, 
	"ID_INSTANSI" VARCHAR2(6), 
	 CONSTRAINT "VACCINE_PK" PRIMARY KEY ("ID_VAKSIN")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "REPORT" ADD CONSTRAINT "REPORT_INSTANSI_FK" FOREIGN KEY ("ID_INSTANSI")
	  REFERENCES  "INSTANSI" ("ID_INSTANSI") ENABLE
/
ALTER TABLE  "REPORT" ADD CONSTRAINT "REPORT_TENAGA_MEDIS_FK" FOREIGN KEY ("NIP")
	  REFERENCES  "TENAGA_MEDIS" ("NIP") ENABLE
/
ALTER TABLE  "TENAGA_MEDIS" ADD CONSTRAINT "TENAGA_MEDIS_INSTANSI_FK" FOREIGN KEY ("ID_INSTANSI")
	  REFERENCES  "INSTANSI" ("ID_INSTANSI") ENABLE
/
ALTER TABLE  "VACCINATION" ADD CONSTRAINT "VACCINATION_PESERTA_VAKSIN_FK" FOREIGN KEY ("NIK")
	  REFERENCES  "PESERTA_VAKSIN" ("NIK") ENABLE
/
ALTER TABLE  "VACCINE" ADD CONSTRAINT "VACCINE_INSTANSI_FK" FOREIGN KEY ("ID_INSTANSI")
	  REFERENCES  "INSTANSI" ("ID_INSTANSI") ENABLE
/
CREATE OR REPLACE EDITIONABLE FUNCTION  "VACCINE_FUNC" (
 n IN NUMBER
) RETURN VARCHAR2
AS
 i NUMBER := n;
 s VARCHAR2(9);
 r NUMBER(2,0);
BEGIN
  WHILE i > 0 LOOP
    r := MOD( i, 999 );
    i := ( i - r ) / 999;
      s := TO_CHAR(r) || s;
    
  END LOOP;
  RETURN LPAD( s, 6, 'V0000' );
END;
/

CREATE OR REPLACE EDITIONABLE FUNCTION  "VACCINATION_FUNC" (
 n IN NUMBER
) RETURN VARCHAR2
AS
 i NUMBER := n;
 s VARCHAR2(9);
 r NUMBER(2,0);
BEGIN
  WHILE i > 0 LOOP
    r := MOD( i, 999 );
    i := ( i - r ) / 999;
      s := TO_CHAR(r) || s;
    
  END LOOP;
  RETURN LPAD( s, 6, '00000' );
END;
/

CREATE OR REPLACE EDITIONABLE FUNCTION  "REPORT_FUNC" (
 n IN NUMBER
) RETURN VARCHAR2
AS
 i NUMBER := n;
 s VARCHAR2(9);
 r NUMBER(2,0);
BEGIN
  WHILE i > 0 LOOP
    r := MOD( i, 999 );
    i := ( i - r ) / 999;
      s := TO_CHAR(r) || s;
    
  END LOOP;
  RETURN LPAD( s, 6, 'L0000' );
END;
/

CREATE OR REPLACE EDITIONABLE FUNCTION  "INSTANSI_FUNC" (
 n IN NUMBER
) RETURN VARCHAR2
AS
 i NUMBER := n;
 s VARCHAR2(9);
 r NUMBER(2,0);
BEGIN
  WHILE i > 0 LOOP
    r := MOD( i, 999 );
    i := ( i - r ) / 999;
      s := TO_CHAR(r) || s;
    
  END LOOP;
  RETURN LPAD( s, 6, 'F0000' );
END;
/

CREATE UNIQUE INDEX  "INSTANSI_PK" ON  "INSTANSI" ("ID_INSTANSI")
/
CREATE UNIQUE INDEX  "PESERTA_VAKSIN_PK" ON  "PESERTA_VAKSIN" ("NIK")
/
CREATE UNIQUE INDEX  "REPORT_PK" ON  "REPORT" ("ID_LAPORAN")
/
CREATE UNIQUE INDEX  "TENAGA_MEDIS_PK" ON  "TENAGA_MEDIS" ("NIP")
/
CREATE UNIQUE INDEX  "VACCINATION_PK" ON  "VACCINATION" ("ID_REGIST")
/
CREATE UNIQUE INDEX  "VACCINE_PK" ON  "VACCINE" ("ID_VAKSIN")
/
 CREATE SEQUENCE   "INSTANSI_1_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION
/
 CREATE SEQUENCE   "REPORT_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION
/
 CREATE SEQUENCE   "VACCINATION_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION
/
 CREATE SEQUENCE   "VACCINE_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "INSTANSI_1_TRIG" 
BEFORE INSERT ON INSTANSI
FOR EACH ROW
BEGIN
  :new.ID_INSTANSI := instansi_func (INSTANSI_1_SEQ.NEXTVAL);
END;

/
ALTER TRIGGER  "INSTANSI_1_TRIG" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "REPORT_TRIG" 
BEFORE INSERT ON REPORT
FOR EACH ROW
BEGIN
  :new.ID_LAPORAN := report_func (REPORT_SEQ.NEXTVAL);
END;

/
ALTER TRIGGER  "REPORT_TRIG" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "VACCINATION_TRIG" 
BEFORE INSERT ON VACCINATION
FOR EACH ROW
BEGIN
  :new.ID_REGIST := vaccination_func (VACCINATION_SEQ.NEXTVAL);
END;

/
ALTER TRIGGER  "VACCINATION_TRIG" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "VACCINE_TRIG" 
BEFORE INSERT ON VACCINE
FOR EACH ROW
BEGIN
  :new.ID_VAKSIN := vaccine_func (VACCINE_SEQ.NEXTVAL);
END;

/
ALTER TRIGGER  "VACCINE_TRIG" ENABLE
/
